version: '3.8'
services:
  webapp:
    image: akt311209/anonyconnect:latest
    container_name: anonyconnect
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage
    environment:
      - NODE_ENV=production
    restart: unless-stopped
